### ISSUE TITLE
I got "Failed to compile with 1 errors" error when running chapter-02/2.7 

### ISSUE THREAD

**Issue by parsllc** [PacktPublishing/Vue.js-3.0-Cookbook#3]
Hi there,
I followed the instructions in Chapter 2 of the book (Creating your first TypeScript Vue
component with vue-class-component), everything went well before running "npm run serve" command
The description of this error that returns in terminal is:

**1. ERROR in src/App.vue:10:6**
This expression is not callable.
Type 'typeof import("PROJECT_DIR/node_modules/vue-class-component/dist/vue-class-component")' has no call
 signatures.
line 10 of App.vue => **@Component**({

**2. ERROR in src/App.vue:15:38**
Type 'typeof import("PROJECT_DIR/node_modules/vue/dist/vue")' is not a constructor function type.
line 15 of App.vue => export default class App extends **Vue**

**3. ERROR in src/components/Counter.vue:17:6**
Unable to resolve signature of class decorator when called as an expression. This expression is not callable.
Type 'typeof import("PROJECT_DIR/node_modules/vue-class-component/dist/vue-class-component")' has no ca
ll signatures.
line 17 of Counter.vue =>**@Component**

**4. ERROR in src/components/Counter.vue:18:42**
Type 'typeof import("PROJECT_DIR/node_modules/vue/dist/vue")' is not a constructor function type.
line 18 of Counter.vue =>export default class Counter extends **Vue**

I spent hours on this but could not fix these errors, Does anyone have an idea? what is the problem?

**Comment by deepesh-packt** [comment]
Hey @parsllc ,
I tried testing it from my end, and it worked well for me without any errors
Can you please create the project from the scratch following the steps mentioned in the book and try again? 
Please do get in touch if you still face issues.

Thanks.

**Comment by xDHILEx** [comment]
@parsllc I ran into the same issues as you. This example uses Vue 2.x, not 3.x

**Comment by deepesh-packt** [comment]
Hi @parsllc 
In the **Preface** section of the book, we have mentioned that - "**Vue 3 beta was the version available at the time of writing this book. All the code will be updated with the final release on the GitHub repository.**" We will update the code to Vue 3 as soon as possible, till then please use Vue 2.6.10 for running the codes. Apologies for the trouble.

**Comment by warrenstephens** [comment]
I have the same errors as shown above -- should they be resolved now in Vue 3 ?

Plus I have the following problem shown in the localhost:8080/#/ window:

> Failed to compile.
>
> ./src/App.vue
> Module not found: Error: Can't resolve 'stylus-loader' in
