### ISSUE TITLE
Error with "vue add ant-design", chapter 9-3

### ISSUE THREAD

**Issue by erlebach** [PacktPublishing/Vue.js-3.0-Cookbook#4]
I followed the instructions in the book in Chapter 9.3, and all went well with the installation of ant-design up to near the end, when I got the following error: 
```
⠋  Running completion hooks...error: Unexpected use of file extension "js" for "./plugins/ant-design-vue.js" (import/extensions) at src/main.js:3:8:
  1 | import { createApp } from 'vue';
  2 | import App from './App.vue';
> 3 | import './plugins/ant-design-vue.js';
    |        ^
  4 |
  5 | createApp(App).mount('#app');
  6 |


1 error found.
```
I have no idea how to proceed. Why would the file extension "js" create a problem? Note that the "./plugins" directory is located in 
```
/node_modules/vue-cli-plugin-ant-design/generator/templates/src/plugins
```
So it is not obvious how the `import` command could possibly work. Any insight to solve this problem would be appreciated as I am a novice in Vue (all versions). Thanks.

   Gordon

**Comment by bloodf** [comment]
It's an ESLint error. You can remove the `.js` extension at the end of the file name without any problem. 

It's an Import rule that checks for file extensions.
